version: "3.9"

services:

  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/testdb
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  ai-agent:
    build: ./ai-agent
    container_name: ai-agent
    restart: always